# Generated by Django 4.2.5 on 2023-10-30 00:18

import Restorations.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donater',
            fields=[
                ('donater_id', models.BigAutoField(db_column='donater_ID', primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=5, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'db_table': 'Donaters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RestoreWork',
            fields=[
                ('restore_id', models.BigAutoField(db_column='restore_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('total_sum', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(max_length=7, validators=[Restorations.models.restoration_status_validate])),
            ],
            options={
                'db_table': 'RestoreWorks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.BigAutoField(db_column='donation_ID', primary_key=True, serialize=False)),
                ('sum', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('card_number', models.BigIntegerField()),
                ('payment_time', models.TimeField(blank=True, null=True)),
                ('donater_id', models.ForeignKey(db_column='donater_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='Restorations.donater')),
                ('restore_id', models.ForeignKey(db_column='restore_ID', on_delete=django.db.models.deletion.CASCADE, to='Restorations.restorework')),
            ],
            options={
                'db_table': 'Donations',
                'managed': True,
            },
        ),
    ]
