# Generated by Django 4.2.5 on 2023-10-30 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restorations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donater',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='restorework',
            options={'managed': False},
        ),
    ]
